import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;

import com.mysql.jdbc.PerConnectionLRUFactory;

public class MySQLAccess {

	public static void main(String args[]) throws SQLException, ClassNotFoundException {
		/**
		 * Returns the Class object associated with the class or interface with
		 * the given string name. Invoking this method is equivalent to:
		 * Class.forName(className, true, currentLoader)
		 **/
		Class.forName("com.mysql.jdbc.Driver");
		// Step 1: Allocate a database "Connection" object
		Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbc", "root", "13245678"); // MySQL

		PreparedStatement preparStatment = conn.prepareStatement("SELECT * FROM login_users WHERE id > ? ");
		System.out.println("Enter ID: ");
		String id = new Scanner(System.in).nextLine();

		preparStatment.setString(1, id);

		System.out.println("***********************************");
		ResultSet results1 = preparStatment.executeQuery();

		while (results1.next()) {

			System.out.println("user name: " + results1.getString(1) + " password:" + results1.getString(2) + " (Id): "
					+ results1.getString(3));
		}
		/**
		 * The object used for executing a static SQL statement and returning
		 * the results it produces.
		 **/
		Statement stmConnection = conn.createStatement();
		String insert = "insert into login_users (username, password) values ('Roni', '132456')";

		stmConnection.executeUpdate(insert);

		/**
		 * A table of data representing a database result set, which is usually
		 * generated by executing a statement that queries the database.
		 **/
		ResultSet results = stmConnection.executeQuery("SELECT * FROM login_users");
		System.out.println("***********************************");
		while (results.next()) {

			System.out.println("user name: " + results.getString(1) + " password:" + results.getString(2) + " (Id): "
					+ results.getString(3));
		}

		String update = "update login_users set username = 'Roze' where id = '3'";
		stmConnection.executeUpdate(update);

		System.out.println("***********************************");

		ResultSet results2 = stmConnection.executeQuery("SELECT * FROM login_users");
		while (results2.next()) {

			System.out.println("user name: " + results2.getString(1) + " password:" + results2.getString(2) + " (Id): "
					+ results2.getString(3));
		}

		String delete = "delete from login_users WHERE username = 'Roze' ";
		stmConnection.executeUpdate(delete);

		System.out.println("***********************************");

		ResultSet results3 = stmConnection.executeQuery("SELECT * FROM login_users");
		while (results3.next()) {

			System.out.println("user name: " + results3.getString(1) + " password:" + results3.getString(2) + " (Id): "
					+ results3.getString(3));
		}

		System.err.println("CoMpLiTeD...");
		conn.close();
	}
}